Background music
timotiousPrime/RocketLauncher pull request #48
Opened 2021-07-29 07:45 UTC by timotiousPrime

Added the background music. It plays depending on if the mute button is pressed or not. I ended up adding the call function (is that the right term?) to the rendering logic. I thought about it, and it is kind rendering the audio, not visually but through the speakers. Let me know if you think I should change it. It works quite well at the moment though

2021-07-29 10:31 UTC, tranhuuphucuong approved these changes
Currently, the audio cannot autoplay, unless users click the sound button, It seems like the browser does not allow a website to play audio without user interaction. So I think it's good for now.

2021-07-29 13:11 UTC, poltak requested changes
This is bugging out pretty badly for me, pausing the music a lot and restarting it. 

I think the restarts is because it's called in the rendering logic which gets re-run whenever state changes and it sets the `currentTime` to 0 each time. Maybe checking if `bgMusic.muted` is different to the value you intend to set before running the setting logic in `playBackgroundMusic` will solve it?

Will look into the pausing issue and see if I can figure out how to reproduce.

RE music not starting until user interaction: Instead of waiting for the user to click unmute, we could make the game start mutation also set the muted state to false. It should still count as user interaction when the user presses the Play button or "Enter", so the music will start when the gameplay does

2021-07-29 13:11 UTC, poltak commented on dom.js
> +export function playBackgroundMusic(boolean) {
I would use a more descriptive name for this variable rather than `boolean`, as it doesn't describe its purpose. It does describe its type, but generally we want to name variables/functions based on their purpose. Maybe `isMuted` (it's a common convention to start boolean var names with "is" or "are")

And this is triggering me because `boolean` is a reserved word in Typescript 😄

2021-07-29 13:32 UTC, poltak commented
RE the seemingly random music pause issue: this happens because if you click the mute button, it remains in focus so next time you press Enter to pause, or Space to unpause, the mute button gets activated again and `click` event handler runs again.

There's a few ways we could approach this. I think just calling `blur()` on the buttons at the end of their event handlers should work. Blur is just the opposite to focus in DOM terminology.
https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event

@tranhuuphucuong any better ideas? 

Also one more thing:
Could you include the relevant license files we need to legally use this music in this PR? I think you just need to copy and paste the license text into a text doc and put it in the repo root (there might be better instructions if you google the license)

2021-07-29 14:56 UTC, tranhuuphucuong commented
Just notice the bugs Jon mentioned, I think it should be easy to fix.
1. RE music not starting until user interaction: Agree with using the play action to play the music, any click is counted as user interaction
2. RE the seemingly random music pause issue:  Just use Blur on the muteBtn at the end of the click handler function. I'm not sure if we should reset the music after users unmute or just keep on playing

2021-07-29 15:17 UTC, timotiousPrime commented
So I think it's best if I just remover the currentTime function and just let it continuously play and if you mute, unmute it will wont restart. The rest of the bugs, ill get to now

2021-07-29 15:19 UTC, tranhuuphucuong commented
@timotiousPrime Yes I think just remove the currentTime for now, see how it goes

2021-07-31 06:24 UTC, tranhuuphucuong approved these changes

2021-08-01 03:40 UTC, poltak approved these changes

2021-08-01 03:40 UTC, merged